// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EasyServerApp.EasyServerDB
{
    public partial class Employee
    {
        public Employee()
        {
            RestaurantTable = new HashSet<RestaurantTable>();
        }

        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Role { get; set; }
        public int EmployeeId { get; set; }

        public List<RestaurantTable> Queue { get; set; }

        public virtual ICollection<RestaurantTable> RestaurantTable { get; set; }
    }
}