// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EasyServerApp.EasyServerDB
{
    public partial class RestaurantTable
    {
        public string Qrcode { get; set; }
        public int TableId { get; set; }
        public int? EmployeeId { get; set; }

        public virtual Employee Employee { get; set; }
    }
}