/*
 * RestaurantTable
 * 
 * This file has been auto generated by EF Core Power Tools.
 * This class represents a row in the RestaurantTable table, where
 * each column is a property
 */
#nullable disable

using System;
using System.Collections.Generic;

namespace EasyServerApp.EasyServerDB
{
    public partial class RestaurantTable
    {
        public string Qrcode { get; set; }
        public int TableId { get; set; }
        public int? EmployeeId { get; set; }

        public virtual Employee Employee { get; set; }
    }
}